#!/usr/bin/env python

import sys

chars = ['o','O','a','A','i','I','l','L','e','E']
leets = ['0','0','4','4','1','1','1','1','3','3']

for line in sys.stdin:
    line = line.strip()
    print(line)

    for i in range(0,len(chars)):
        if chars[i] in line:
            print(line.replace(chars[i],leets[i]))

    for i in range(0,len(chars)):
        line = line.replace(chars[i],leets[i])

    print(line)
