#!/usr/bin/env python

import sys

for line in sys.stdin:
    words = line.strip().split(' ')
    for i in range(0,len(words)):
        print(' '.join(words[i:]))
    for i in range(len(words),0,-1):
        print(' '.join(words[:i]))
